version: 2.1
workflows:
  test:
    jobs:
      - checkout_code
      - fastlane_test:
          requires:
            - checkout_code
      - test:
          requires:
            - checkout_code
jobs:
  test:
    executor: react-native/linux_js
    steps:
      - attach_workspace:
          at: .
      - react-native/yarn_install
      - run:
          command: yarn lint
          name: Run ESLint
      - run:
          command: yarn test
          name: Run Tests
  checkout_code:
    executor: react-native/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
  fastlane_test:
    executor: react-native/linux_js
    steps:
      - attach_workspace:
          at: .
      - react-native/yarn_install
      - run:
          command: |
            cat /etc/os-release
            sudo apt update
            sudo apt install ruby-full
            ruby --version
            sudo apt install git curl libssl-dev libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev
            curl -sL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash -
            echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
            echo 'eval "$(rbenv init -)"' >> ~/.bashrc
            source ~/.bashrc
            rbenv install 2.5.1
            rbenv global 2.5.1
            ruby --version
            export LC_ALL=en_US.UTF-8
            export LANG=en_US.UTF-8es
            sudo gem install fastlane -NV
            which fastlane
            cd android
            fastlane android test
          name: Run Fastlane Test
#      - run:
#          command: ./gradlew build
#      - run:
#          name: Execute fastlane test
#          command: bundle exec fastlane test
orbs:
  android: circleci/android@0.2.0
  react-native: react-native-community/react-native@4.4.2