version: 2.1
workflows:
  test:
    jobs:
      - checkout_code
      - fastlane_test:
          requires:
            - checkout_code
      - test:
          requires:
            - checkout_code
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: .
      - run:
          command: yarn lint
          name: Run ESLint
#      - run:
#          command: yarn test
#          name: Run Tests
  checkout_code:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn install
      - persist_to_workspace:
          paths: .
          root: .
  fastlane_test:
    docker:
      - image: circleci/android:api-27-node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: fastlane install
          command: |
            cd android
            bundle install
      - run:
          name: fastlane tests
          command: |
            cd android
            bundle exec fastlane test
      - store_artifacts:
          path: fastlane/report.xml
          destination: test-results
      - run:
          name: fastlane alpha
          command: |
            cd android
            bundle exec fastlane alpha
#      - run:
#          command: ./gradlew build
#      - run:
#          name: Execute fastlane test
#          command: bundle exec fastlane test
orbs:
  android: circleci/android@0.2.0
  react-native: react-native-community/react-native@4.4.2