version: 2.1
workflows:
  # TODO Remove Test
  test:
    jobs:
      - checkout_code:
          merged: false
          commit: true
          context: shara-dev
          filters:
            branches:
              only:
                - feature/auto-versioning
  internal:
    jobs:
      - checkout_code:
          context: shara-dev
          filters:
            branches:
              ignore:
                - master
                - develop
                - discovery
                - feature/auto-versioning
      - test:
          requires:
            - checkout_code
          filters:
            branches:
              ignore:
                - master
                - develop
                - discovery
                - feature/auto-versioning
      - fastlane:
          context: shara-dev
          lane: internal
          requires:
            - checkout_code
            - test
          filters:
            branches:
              ignore:
                - master
                - develop
                - discovery
                - feature/auto-versioning
  discovery:
    jobs:
      - checkout_code:
          context: shara-dev
          filters:
            branches:
              only:
                - develop
                - discovery
                - master
      - test:
          requires:
            - checkout_code
      - request-approval:
          type: approval
          requires:
            - checkout_code
            - test
      - fastlane:
          context: shara-dev
          lane: play
          track: internal
          requires:
            - request-approval
          filters:
            branches:
              only:
                - discovery
      # TODO Production Release Workflow
jobs:
  checkout_code:
    docker:
      - image: circleci/node:12
    parameters:
      merged:
        type: boolean
        default: false
      commit:
        type: boolean
        default: false
    steps:
      - checkout
      - run:
          name: Yarn Install Dependencies
          command: yarn install
      - when:
          condition: <<parameters.merged>>
          steps:
            - run:
                name: Auto-versioning >>  When Master, Discovery or Develop bump patch
                command: |
                  CURRENT_VERSION=$(jq ".version" -r package.json)
                  NEW_VERSION=$(./bin/semver bump patch ${CURRENT_VERSION});
                  jq ".version=\"${NEW_VERSION}\"" package.json > package.json-new && mv package.json-new package.json
                  echo "export NEW_VERSION=${NEW_VERSION}" >> $BASH_ENV
                  echo "CIRCLE_BUILD_NUM: ${CIRCLE_BUILD_NUM}"
                  echo "CURRENT_VERSION: ${CURRENT_VERSION}"
                  echo "NEW_VERSION: ${NEW_VERSION}"
      - unless:
          condition: <<parameters.merged>>
          steps:
            - run:
                name: Auto-versioning >> When unmerged i.e. feature branches, bump build
                command: |
                  CURRENT_VERSION=$(jq ".version" -r package.json)
                  NEW_VERSION=$(./bin/semver bump build "build.${CIRCLE_BUILD_NUM}" ${CURRENT_VERSION});
                  jq ".version=\"${NEW_VERSION}\"" package.json > package.json-new && mv package.json-new package.json
                  echo "export NEW_VERSION=${NEW_VERSION}" >> $BASH_ENV
                  echo "CIRCLE_BUILD_NUM: ${CIRCLE_BUILD_NUM}"
                  echo "CURRENT_VERSION: ${CURRENT_VERSION}"
                  echo "NEW_VERSION: ${NEW_VERSION}"
      # TODO Should happen after tests, build and deploy
      - when:
          condition: <<parameters.commit>>
          steps:
            - add_ssh_keys:
                fingerprints:
                  - "90:6e:55:bd:ec:dd:c7:3b:72:d9:11:1c:74:e6:13:98"
            - run:
                name: Commit and push version update
                command: |
                  git config --global user.email "pipeline@circleci.com" && git config --global user.name "CircleCI Pipeline"
                  git commit -am "Bumped version to ${NEW_VERSION} [skip ci]"
                  git push --set-upstream origin ${CIRCLE_BRANCH}
      - run:
          name: Setup Credentials
          command: |
            echo -n ${FIREBASE_GOOGLE_SERVICES_KEY} | base64 -d -i > android/app/google-services.json
            echo -n ${GOOGLE_PLAY_STORE_SERVICE_ACCOUNT_KEY} | base64 -d -i > android/google-play-store-service-account.json
            echo -n ${SHARE_ANDROID_KEYSTORE} | base64 -d -i > android/app/shara.keystore
            echo -n ${SHARA_MOBILE_ENV} | base64 -d -i > .env
            echo -n ${SHARA_ANDROID_KEYSTORE_CREDENTIALS} | base64 -d -i >> android/gradle.properties
            sed -i "s#SHARA_VERSION_CODE#${CIRCLE_BUILD_NUM}#g" android/app/build.gradle
            sed -i "s#SHARA_VERSION_NAME#${NEW_VERSION}#g" android/app/build.gradle

      # TODO Commit version updates
      # TODO Push version updates
      - persist_to_workspace:
          paths: .
          root: .
  test:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: .
      - run:
          command: yarn lint
          name: Run ESLint
  fastlane:
    parameters:
      lane:
        type: string
        default: test
      track:
        type: string
        default: internal
    docker:
      - image: circleci/android:api-27-node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Fastlane & Firebase tools
          command: |
            cd android
            bundle install
            curl -sL https://firebase.tools | bash
      - run:
          name: Fastlane <<parameters.lane>>
          command: |
            cd android
            bundle exec fastlane <<parameters.lane>>
          environment:
            GOOGLE_PLAY_TRACK: <<parameters.track>>
      - store_artifacts:
          path: fastlane/report.xml
          destination: test-results
orbs:
  android: circleci/android@0.2.0
  react-native: react-native-community/react-native@4.4.2